export const photos = [
    {
        src:'images/design/gambar1.jpg',
        width:4,
        height:5
    },
    {
        src:'images/design/gambar2.jpg',
        width:6,
        height:7
    },
    {
        src:'images/design/gambar3.jpg',
        width:6,
        height:7
    },
    {
        src:'images/design/gambar4.jpg',
        width:10,
        height:7
    },
    {
        src:'images/design/gambar5.jpg',
        width:10,
        height:7
    },
    {
        src:'images/design/gambar6.jpg',
        width:5.5,
        height:7
    },
    {
        src:'images/design/gambar7.jpg',
        width:5.5,
        height:7
    },
    {
        src:'images/design/gambar9.jpg',
        width:11,
        height:7
    },
    {
        src:'images/design/gambar10.jpg',
        width:6,
        height:7
    },
    {
        src:'images/design/gambar11.jpg',
        width:9,
        height:7
    },
    {
        src:'images/design/gambar12.jpg',
        width:6,
        height:7
    },
    {
        src:'images/design/gambar13.jpg',
        width:10,
        height:7
    },
    {
        src:'images/design/gambar14.jpg',
        width:6,
        height:7
    },
    
]